# Generated by Django 3.0.5 on 2020-10-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadacha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esep',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='esep',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата принятия'),
        ),
    ]
