# Generated by Django 3.0.5 on 2020-10-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadacha', '0002_auto_20201008_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esep',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Файл'),
        ),
    ]
