# Generated by Django 3.0.5 on 2020-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadacha', '0003_auto_20201008_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esep',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='esep',
            name='name',
        ),
        migrations.AddField(
            model_name='esep',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='esep',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграмм'),
        ),
        migrations.AddField(
            model_name='esep',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ватсап'),
        ),
        migrations.AlterField(
            model_name='esep',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='esep',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл'),
        ),
    ]
